//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace extreemt
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheque
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int amount { get; set; }
        public System.DateTime chequeDate { get; set; }
        public string chequeType { get; set; }
    
        public virtual user user { get; set; }
    }
}
