//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace extreemt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class extreemtEntities : DbContext
    {
        public extreemtEntities()
            : base("name=extreemtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> categories { get; set; }
        public DbSet<cheque> cheques { get; set; }
        public DbSet<photo> photos { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<Transfer> Transfers { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<userPayProduct> userPayProducts { get; set; }
    }
}
