//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace extreemt
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.photos = new HashSet<photo>();
            this.userPayProducts = new HashSet<userPayProduct>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int count { get; set; }
        public System.DateTime date { get; set; }
        public int price { get; set; }
        public int categoryId { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<photo> photos { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<userPayProduct> userPayProducts { get; set; }
    }
}
