//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace extreemt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int id { get; set; }
        public int transferFrom { get; set; }
        public int transferTo { get; set; }
        public System.DateTime transferDate { get; set; }
        public int amount { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
