//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace extreemt
{
    using System;
    using System.Collections.Generic;
    
    public partial class userPayProduct
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int productId { get; set; }
        public System.DateTime date { get; set; }
        public string productName { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
